# Generated by Django 4.2.5 on 2023-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegramApiId', models.CharField(blank=True, max_length=50, null=True)),
                ('telegramApiHash', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
