# Generated by Django 4.2.5 on 2023-11-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('telegramId', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('parse', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('hasImage', models.BooleanField(default=False)),
                ('hasVideo', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('telegramGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_group_messages', to='api.telegramgroup')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessageSnapshot',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('snapshotDate', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('telegramMessage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_message_snapshots', to='api.telegrammessage')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroupSnapshot',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('snapshotDate', models.DateTimeField(auto_now_add=True)),
                ('subs', models.IntegerField(blank=True, null=True)),
                ('numMessages', models.IntegerField(blank=True, null=True)),
                ('telegramGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_group_snapshots', to='api.telegramgroup')),
            ],
        ),
        migrations.AddField(
            model_name='narrative',
            name='telegramGroups',
            field=models.ManyToManyField(blank=True, related_name='telegram_groups', to='api.telegramgroup'),
        ),
    ]
