# Generated by Django 4.2.5 on 2023-11-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_telegramgroup_telegrammessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='telegramPhone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
