# Generated by Django 4.2.5 on 2023-11-07 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_appsettings_telegramphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
